apiVersion: v1
kind: ServiceAccount
metadata:
  name: acme-fitness-sa
  namespace: tanzu-fluxcd-packageinstalls
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acme-fitness-sa-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-cluster-role-binding-acme-fitness-sa
subjects:
- kind: ServiceAccount
  name: acme-fitness-sa
  namespace: tanzu-fluxcd-packageinstalls
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acme-fitness-sa-cluster-role
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: acme-fitness
  namespace: tanzu-fluxcd-packageinstalls
spec:
  packageRef:
    refName: acme-fitness.external.demo-dependencies.learn
    versionSelection:
      prereleases: {}
      constraints: 1.0.0
  serviceAccountName: acme-fitness-sa
  # values:
  # - secretRef:
  #     name: tap-values
