apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels:
    blk.com/client: client-4
    blk.com/region: east
    blk.com/app: app-1-guestbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        blk.com/client: client-4
        blk.com/region: east
        blk.com/app: app-1-guestbook
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
