apiVersion: v1
kind: ServiceAccount
metadata:
  name: acme-fitness-sa
  namespace: package-installs
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acme-fitness-sa-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-cluster-role-binding-acme-fitness-sa
subjects:
- kind: ServiceAccount
  name: acme-fitness-sa
  namespace: package-installs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acme-fitness-sa-cluster-role
