apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    vmware.com/client: client-3
    vmware.com/region: east
    vmware.com/app: app-1-guestbook
    app.kubernetes.io/part-of: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
