apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    tkg.tanzu.vmware.com/skip-tls-verify: ""
    tkg.tanzu.vmware.com/tkg-http-proxy: ""
    tkg.tanzu.vmware.com/tkg-https-proxy: ""
    tkg.tanzu.vmware.com/tkg-ip-family: ""
    tkg.tanzu.vmware.com/tkg-no-proxy: ""
    tkg.tanzu.vmware.com/tkg-proxy-ca-cert: ""
  finalizers:
  - cluster.cluster.x-k8s.io
  - tkg.tanzu.vmware.com/addon
  labels:
    argocd.argoproj.io/instance: clusters
    cluster.x-k8s.io/cluster-name: blk-sandbox-2
    run.tanzu.vmware.com/tkr: v1.23.15---vmware.1-tkg.4
    topology.cluster.x-k8s.io/owned: ""
  name: blk-sandbox-2
  namespace: admin
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.20.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/16
  controlPlaneEndpoint:
    host: 10.220.14.126
    port: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: blk-sandbox-2-ndr4l
    namespace: admin
  infrastructureRef:
    apiVersion: vmware.infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereCluster
    name: blk-sandbox-2-7tnqp
    namespace: admin
  topology:
    class: tanzukubernetescluster
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
    - name: vmClass
      value: best-effort-medium
    - name: storageClass
      value: vc01cl01-t0compute
    - name: storageClasses
      value:
      - vc01cl01-t0compute
    - name: defaultStorageClass
      value: vc01cl01-t0compute
    - name: TKR_DATA
      value:
        v1.23.15+vmware.1:
          kubernetesSpec:
            coredns:
              imageTag: v1.8.6_vmware.11
            etcd:
              imageTag: v3.5.6_vmware.2
            imageRepository: localhost:5000/vmware.io
            kube-vip: null
            pause:
              imageTag: "3.6"
            version: v1.23.15+vmware.1
          labels:
            image-type: vmi
            os-arch: amd64
            os-name: photon
            os-type: linux
            os-version: "3"
            run.tanzu.vmware.com/os-image: ob-21554505-photon-3-amd64-vmi-k8s-v1.23.15---vmware.1-tkg.4
            run.tanzu.vmware.com/tkr: v1.23.15---vmware.1-tkg.4
            vmi-name: ob-21554505-photon-3-amd64-vmi-k8s-v1.23.15---vmware.1-tkg.4
          osImageRef:
            name: ob-21554505-photon-3-amd64-vmi-k8s-v1.23.15---vmware.1-tkg.4
    - name: ntp
      value: time1.oc.vmware.com
    - name: extensionCert
      value:
        contentSecret:
          key: tls.crt
          name: blk-sandbox-2-extensions-ca
    - name: user
      value:
        passwordSecret:
          key: ssh-passwordkey
          name: blk-sandbox-2-ssh-password-hashed
        sshAuthorizedKey: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKEOKiPJVefZsV26d1wNMbGUwdMonDzaD1XfrrjuLUhldNZx9kPFgOaF4SSVSiJfMez9HquGWmRJEyAvFL2tH1jSeMp3Ds+qWht1LpthP62uMRr9shOgmotXmhLyhPkYz8MReFMb4CFh/9WfNMJNzVGBu4ApwU6SDZhIiutbeltrsU8nDx2hzJQwuNUfWa5yYBvWbHEvp57krRUKVtqwmRSIjvfTIiuIRVrZlSwTvXvT8gfF4LA9LS0LoxFTjbEyqJ8EliJ2B4unvtjGtYNG1MDgC0xe9wR24kmUochYkDynFDlB43A1hYFtslfLOrmg2Vxqa5XPu/VS0BpDVeA5NM+SFkeEtdjeqgBayjgZVdQVrDcZiiuPaxeBGcWRweVaxjROWe5U0HVRY8wr2XYQfAhG1Hau5URv/j6nGZVsEvsoufG3Xmlxkuqfrc/K7Y28YUNBOa1jawmEeU8J/FTi3VlAAz5zUgTgIb7pKwsSn+3pr6xcGBsnWQ+DwtMvoXvFspkUTQp0VLpT4odb1LaRISFcVTr1gqon0kZeXyQXchTo4i6dB0kDaVOQ3TCzTGv0VvpEel/gDdgU9jFxg2FQhTz+EOhNm4tNie+usXyBajNenS7bfXLkYIyUYUKstlYE5Qb41IhZbJNPUK171XA4+6+a0h/ni0+aGr0dR9JgKlVw==
    - name: clusterEncryptionConfigYaml
      value: LS0tCmFwaVZlcnNpb246IGFwaXNlcnZlci5jb25maWcuazhzLmlvL3YxCmtpbmQ6IEVuY3J5cHRpb25Db25maWd1cmF0aW9uCnJlc291cmNlczoKICAtIHJlc291cmNlczoKICAgIC0gc2VjcmV0cwogICAgcHJvdmlkZXJzOgogICAgLSBhZXNjYmM6CiAgICAgICAga2V5czoKICAgICAgICAtIG5hbWU6IGtleTEKICAgICAgICAgIHNlY3JldDogZXBHZmptVCtXSjZuR0dFUCtsaWl0ejBBUnZJL1BHMGFXU3M2elVUc2hoMD0KICAgIC0gaWRlbnRpdHk6IHt9Cg==
    version: v1.23.15+vmware.1
    workers:
      machineDeployments:
      - class: node-pool
        metadata: {}
        name: md-0
        replicas: 3
        variables:
          overrides:
          - name: vmClass
            value: best-effort-medium
          - name: storageClass
            value: vc01cl01-t0compute