apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: acme-fitness
  namespace: tanzu-fluxcd-packageinstalls
spec:
  packageRef:
    versionSelection:
      constraints: 1.0.1
