apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    blk.com/client: client-2
    blk.com/region: west
    blk.com/app: app-1-guestbook
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
