apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: acme-fitness
  namespace: package-installs
spec:
  packageRef:
    versionSelection:
      constraints: 1.0.2
  values:
  - secretRef:
      name: blk-values
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: blk-values
  namespace: package-installs
spec:
  fromNamespace: blk-platform