apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels:
    vmware.com/client: client-2
    vmware.com/region: west
    vmware.com/app: app-1-guestbook
    app.kubernetes.io/part-of: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        vmware.com/client: client-2
        vmware.com/region: west
        vmware.com/app: app-1-guestbook
        app.kubernetes.io/part-of: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
